feat: add product pages
UMAprotocol/website pull request #138
Opened 2022-03-14 18:38 UTC by daywiss

Signed-off-by: David <david@umaproject.org>

This adds 6 product pages for desktop and mobile views. To QA go to the product link in nav bar and click any of the specific products. 

This is missing the animations showing the Hero text, we will need to do this as a separate pr as it seems pretty tricky.

2022-03-17 15:48 UTC, Tommy1231232 commented on pages/products/success-tokens.tsx
> +          href: "https://docs.google.com/spreadsheets/d/1wRYgPVIjEyk6ADi1f0IKhKXoN3iaZRG7v3Iza-HhNIw/edit#gid=53260911",
Update this link to: https://forum.shapeshift.com/t/success-token-proposal-discussion/599

2022-03-18 13:47 UTC, amateima commented
I think https://github.com/tameemsafi/typewriterjs is the easiest way to add the typewriting effect

2022-03-18 15:32 UTC, Gamaranto approved these changes

2022-03-18 17:08 UTC, daywiss commented on public/images/products/UMA-Sherlock.svg
> +</svg>
i moved logo images there and re-used them if they already exists

2022-03-18 17:08 UTC, daywiss commented on components/ProductPageTemplate/components.tsx
> +  margin: 8px 0;
good to know

2022-03-18 17:08 UTC, daywiss commented on components/ProductPageTemplate/components.tsx
> +  padding 16px 0;
fixed

2022-03-18 18:29 UTC, Tommy1231232 requested changes

2022-03-18 18:29 UTC, Tommy1231232 commented on pages/products/kpi-options.tsx
> +        "Example UI for claiming and viewing KPI Options tokens for your community",
<img width="359" alt="Screen Shot 2022-03-18 at 1 59 46 PM" src="https://user-images.githubusercontent.com/71620056/159058122-7c644358-4234-4ec8-9b4b-c1862213544d.png">


Lets update the color of the font "Example UI...." to that of the above designs

2022-03-18 18:29 UTC, Tommy1231232 commented on pages/products/kpi-options.tsx
> +        details: "Define the KPI (Key Perfomance Index) you want to hit.",
Update to "Key Performance Index (KPI)"

2022-03-18 18:29 UTC, Tommy1231232 commented on pages/products/kpi-options.tsx
> +          "The tokens to your target community and advertise your campaign.",
Lowercase the "T" in "The"

2022-03-18 18:29 UTC, Tommy1231232 commented on pages/products/success-tokens.tsx
> +        "put vesting agreements on chain",
update to on-chain

2022-03-18 18:29 UTC, Tommy1231232 commented on pages/products/success-tokens.tsx
> +        details: "No lawyers or off-chain brokers required.",
Remove the period

2022-03-18 18:29 UTC, Tommy1231232 commented on pages/products/range-tokens.tsx
> +          "Treasuries who want to borrow stablecoins against a project token without the immediate regulatory implications of conducting a sale.",
Per designs, lets have "regulatory" be on the second line

2022-03-18 18:29 UTC, Tommy1231232 commented on pages/products/lsp.tsx
> +          "Accommodates various financial payout types and products with minimal changes",
Lets put a period at the end of this

2022-03-18 19:27 UTC, Tommy1231232 approved these changes

2022-03-18 19:29 UTC, merged